repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.0.1
    hooks:
      - id: reorder-python-imports
        args:
          - --py39-plus
          - --application-directories=.:src
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [ -l 120 ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        additional_dependencies:
          - attrs>=21.1
          - types-attrs
          - types-requests
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: [ --py39-plus ]
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.5.1
    hooks:
      - id: pip-compile
        name: pip-compile setup.py
        args: [ setup.py ]
        files: ^(setup\.py|requirements\.txt)$
        stages: [manual]
