#
# See https://circleci.com/docs/2.0/configuration-reference for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: cimg/python:3.9.12

    steps:
      - checkout

      # Cache dependencies
      - restore_cache:
          keys:
          - jiradeps-dependencies-{{ checksum "requirements-dev.txt" }}
          # fallback to using the latest cache if no exact match is found
          - jiradeps-dependencies-

      - run:
          name: install graphviz
          command: |
            sudo apt-get update && sudo apt-get install -y graphviz

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install pip-tools
            pip-compile
            pip install -U -r requirements-dev.txt
            pip install .

      - save_cache:
          paths:
            - ./venv
          key: jiradeps-dependencies-{{ checksum "requirements-dev.txt" }}

      - run:
          name: run pre-commit
          command: |
            . venv/bin/activate
            pre-commit run -a

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest --junit-xml=test-results/pytest/result.xml

      - store_artifacts:
          path: test-results/pytest
          destination: pytest

      - store_test-results:
          path: test-results/pytest
